name: Deploy to Gaia

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, gaia]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Secrets
        env:
          METUBE_COOKIES_TXT: ${{ secrets.METUBE_COOKIES_TXT }}
        run: |
          chmod +x scripts/ensure_secret.sh
          # Generate versioned secret for MeTube Cookies
          echo "METUBE_COOKIES_SECRET_NAME=$(echo "$METUBE_COOKIES_TXT" | ./scripts/ensure_secret.sh apollo_metube_cookies)" >> $GITHUB_ENV

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: registry.tienzo.net
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_RAW_PASSWORD }}

      - name: Deploy Stack
        env:
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          LLDAP_LDAP_BASE_DN: ${{ vars.LLDAP_LDAP_BASE_DN }}
          LLDAP_LDAP_USER_PASS: ${{ secrets.LLDAP_LDAP_USER_PASS }}
          LLDAP_JELLYFIN_USERS_GROUP: ${{ vars.LLDAP_JELLYFIN_USERS_GROUP }}
          LLDAP_JELLYFIN_ADMINS_GROUP: ${{ vars.LLDAP_JELLYFIN_ADMINS_GROUP }}
          JELLYSTAT_JWT_SECRET: ${{ secrets.JELLYSTAT_JWT_SECRET }}
          JELLYSTAT_DB_PASSWORD: ${{ secrets.JELLYSTAT_DB_PASSWORD }}
          REGISTRY_PREFIX: ${{ vars.REGISTRY_PREFIX }}
          RADARR_API_KEY: ${{ secrets.RADARR_API_KEY }}
          SONARR_API_KEY: ${{ secrets.SONARR_API_KEY }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh "apollo-core" docker-compose.yml
